### PR TITLE
Add support for getting the UUID of a device

### LINKED ISSUE #55: Adding support for getting the UUID
Currently there is no way to get the UUID of a device. I'd like to add this feature.

It's a matter of calling [`cuDeviceGetUuid()`](https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__DEVICE.html#group__CUDA__DEVICE_1g987b46b884c101ed5be414ab4d9e60e4), which is already part of cuda-sys. There is also a [`cuDeviceGetUuid_v2()`](https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__DEVICE.html#group__CUDA__DEVICE_1gdf3394a41af9cdb9f653386ed4991a1f), but that's a very recent addition (CUDA 11.4), so I would ignore it for now as `cuda-sys` is on CUDA 10.2 anyway.

I would implement `Device::uuid()`, similarly to the existing [`Device::name()`](https://bheisler.github.io/RustaCUDA/rustacuda/device/struct.Device.html#method.name).

Though `cuDeviceGetUuid()` is only available on `cuda-driver-sys` 0.3, which seems to be the successor of `cuda-sys` 0.2. Upgrading to it seems to work with minimal changes, I can also provide a PR for that (my current version of those changes is at https://github.com/vmx/RustaCUDA/tree/uuid).

### PR DESCRIPTION
**Pull request by vmx**
This PR consists of two independent commits, the first one is the upgrade to `cuda-driver-sys` 0.3, the second one is the actual implementation API for getting the UUID.

Let me know if you'd prefer to have two separate PR, having it in a single one was just quicker for me as I had this branch already available.

Closes #55.

### CODE REVIEW

**Comment by vmx** [comment]
I forgot to add a changelog entry, I'll do that tomorrow.

**Comment by vmx** [comment]
Is there anything missing/I could help with to get this one merged? Or do I just need to be patient, which is also fine :)

**Comment by bheisler** [comment]
Hey, thanks for the pull request and for your patience so far.

The code looks good to me. Unfortunately I lost my CUDA development setup in an SSD crash a couple months ago and haven't set up a replacement yet, so I can't run the tests to verify that this actually works. I don't want to publish code I haven't tested, so I'll have to ask you to remain patient for a bit longer. I'll try to get that done by the end of this week.

**Comment by bheisler** [comment]
Merged. Thanks!

**Comment by vmx** [comment]
Thanks a lot, for getting setup again so quickly.

**Pull request merged**
